"""Deterministic indicator pipeline for XAUUSD institutional trading.

Execution order
---------------
1. ATR   — Average True Range (Wilder's smoothing).
           Used downstream for stop-loss sizing and liquidity-sweep detection.
           Requires: high, low, close.

2. EMA   — Exponential Moving Average, SMA-seeded recursive formula.
           Used downstream for trend bias (bullish/bearish regime) and as a
           dynamic support/resistance reference for the signal engine.
           Requires: close.

3. RSI   — Relative Strength Index (Wilder's smoothing).
           Used downstream as a momentum filter: confirms or rejects signals
           generated by the structural analysis layer.
           Requires: close.

4. VWAP  — Volume-Weighted Average Price (cumulative session).
           Used downstream to gauge institutional positioning — price above
           VWAP favours longs; below favours shorts.
           Requires: high, low, close, volume.

The order above is fixed.  No indicator may depend on the output of one that
follows it in the pipeline; any future indicator that does must be appended
after all current ones.
"""

from __future__ import annotations

import pandas as pd

from indicators.atr import compute_atr
from indicators.ema import compute_ema
from indicators.rsi import compute_rsi
from indicators.vwap import compute_vwap

# Columns required by each stage of the pipeline, checked before any
# computation begins so failures are immediate and descriptive.
_REQUIRED_ATR  = {"high", "low", "close"}
_REQUIRED_EMA  = {"close"}
_REQUIRED_RSI  = {"close"}
_REQUIRED_VWAP = {"high", "low", "close", "volume"}


def _validate_columns(df: pd.DataFrame, required: set[str], stage: str) -> None:
    missing = required - set(df.columns)
    if missing:
        raise ValueError(
            f"compute_indicators() [{stage}]: missing required column(s): "
            f"{sorted(missing)}"
        )


def compute_indicators(
    df: pd.DataFrame,
    *,
    atr_period: int = 14,
    ema_periods: list[int] | None = None,
    rsi_period: int = 14,
    include_vwap: bool = True,
) -> pd.DataFrame:
    """Run the deterministic indicator pipeline and return an enriched DataFrame.

    All indicators are computed in a fixed, dependency-ordered sequence (ATR →
    EMA → RSI → VWAP).  Column requirements are validated up-front so that
    any missing data raises an explicit ``ValueError`` before any computation
    is attempted.

    Parameters
    ----------
    df : pd.DataFrame
        OHLCV candle data.  Required columns depend on which indicators are
        enabled — see module docstring for per-stage requirements.
    atr_period : int
        Wilder ATR smoothing period.  Default 14.
    ema_periods : list[int] | None
        EMA periods to compute.  Each becomes an ``EMA_{period}`` column.
        Defaults to ``[20, 50, 200]``.
    rsi_period : int
        Wilder RSI smoothing period.  Default 14.
    include_vwap : bool
        Whether to append the cumulative VWAP column.  Set ``False`` when
        volume data is unavailable.  Default ``True``.

    Returns
    -------
    pd.DataFrame
        A copy of ``df`` (original is never mutated) with indicator columns
        appended in pipeline order: ``ATR``, ``EMA_*``, ``RSI``, ``VWAP``.

    Raises
    ------
    ValueError
        If any required column for an enabled indicator is absent, or if a
        period parameter is invalid (propagated from individual functions).
    """
    if ema_periods is None:
        ema_periods = [20, 50, 200]

    # ------------------------------------------------------------------ #
    # Up-front column validation — fail fast before touching any data     #
    # ------------------------------------------------------------------ #
    _validate_columns(df, _REQUIRED_ATR, "ATR")
    _validate_columns(df, _REQUIRED_EMA, "EMA")
    _validate_columns(df, _REQUIRED_RSI, "RSI")
    if include_vwap:
        _validate_columns(df, _REQUIRED_VWAP, "VWAP")

    # Immutability: all writes go to this copy; df is never touched.
    out = df.copy()

    # ------------------------------------------------------------------ #
    # Stage 1: ATR — must run first; output consumed by SL/sweep logic    #
    # ------------------------------------------------------------------ #
    out["ATR"] = compute_atr(df, period=atr_period)

    # ------------------------------------------------------------------ #
    # Stage 2: EMA — trend bias; each period is independent of the others #
    # ------------------------------------------------------------------ #
    for period in ema_periods:
        series = compute_ema(df, period=period)
        out[series.name] = series

    # ------------------------------------------------------------------ #
    # Stage 3: RSI — momentum filter; runs after EMAs by convention       #
    # ------------------------------------------------------------------ #
    out["RSI"] = compute_rsi(df, period=rsi_period)

    # ------------------------------------------------------------------ #
    # Stage 4: VWAP — institutional positioning; last (needs volume)      #
    # ------------------------------------------------------------------ #
    if include_vwap:
        out["VWAP"] = compute_vwap(df)

    return out

